{{- if .Values.telegram.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: telegram-secret
type: Opaque
data:
  chat-id: {{ .Values.telegram.chat | b64enc }}
  token: {{ .Values.telegram.token | b64enc }}
{{- end }}