apiVersion: v1
kind: Secret
metadata:
  name: cloud-config-secret
type: Opaque
data:
  username: {{ .Values.config.server.username | b64enc }}
  password: {{ .Values.config.server.password | b64enc }}
