apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloud-config.fullname" . }}
  labels:
{{ include "cloud-config.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cloud-config.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cloud-config.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: cloud-config-secret
                  key: username
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud-config-secret
                  key: password
            - name: GIT_URI
              value: {{ .Values.git.uri }}
            {{ if .Values.git.credentials.enabled -}}
            - name: GIT_USER
              valueFrom:
                secretKeyRef:
                  name: git-secret
                  key: username
            - name: GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: git-secret
                  key: password
            {{- end }}
            {{ if .Values.spring.boot.admin.enabled -}}
            - name: SPRING_BOOT_ADMIN_URL
              value: {{ .Values.spring.boot.admin.url }}
            - name: SPRING_BOOT_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spring-admin-secret
                  key: username
            - name: SPRING_BOOT_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-admin-secret
                  key: password
            {{ if .Values.spring.boot.admin.enabled -}}
            - name: BASE_URL
              value: http{{ if .Values.ingress.tls }}s{{ end }}://{{ .Values.ingress.host }}
            {{- end }} 
            {{- end }}

          resources:
          {{- toYaml .Values.resources | nindent 12 }}
