{{- if .Values.git.credentials.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: git-secret
type: Opaque
data:
  username: {{ .Values.git.user | b64enc }}
  password: {{ .Values.git.password | b64enc }}
{{- end }}