{{- if .Values.spring.boot.admin.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: spring-admin-secret
type: Opaque
data:
  username: {{ .Values.spring.boot.admin.username | b64enc }}
  password: {{ .Values.spring.boot.admin.password | b64enc }}
{{- end }}