apiVersion: v1
kind: PersistentVolume
metadata:
  name: unseen-db-storage
spec:
  capacity: 
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /database/unseen
