# Default values for cloud-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: torresjb
  name: spring-cloud-config-server
  version: 0.1.8
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8888

config:
  server:
    user: user
    password: password

spring:
  boot:
    admin:
      enabled: false
      url:
      username:
      password:

git:
  credentials:
    enabled: false
  user: user
  password: password
  uri: https://github.com/spring-cloud-samples/config-repo

ingress:
  enabled: false
  controller:
    class: nginx
  host: cloud-config.local
  path: /
  tls:
    enabled: false
    cert_manager:
      cluster_issuer:
